# fly.toml app configuration file generated for frontend-app-weathered-leaf-9842 on 2025-09-18T23:35:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'frontend-app-weathered-leaf-9842'
primary_region = 'bos'

[build]


[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
NEXT_PUBLIC_BACKEND_URL = "https://backend-api-summer-log-9036.fly.dev"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
